# Generated by Django 2.2.5 on 2019-09-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
