# Generated by Django 2.2.5 on 2019-09-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
