# Generated by Django 2.2.5 on 2019-09-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190924_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
