# Generated by Django 2.2.5 on 2019-09-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190924_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
